### ISSUE TITLE
incompatibility with latest think_core (2.0.0.rc.1 )

### ISSUE THREAD

**Issue by postite** [haxetink/tink_querystring#18]
tink web does not accept query parameters when using think core 2.0.0 rc
reproducible example :

html:

    -lib tink_querystring
    -main QueryDebug
    --interp

QueryDebug:

    typedef Post = {
    title:String, 
    body:String,
    tags:Array<String>,
      }
    class QueryDebug{
    static function main() {

    var post:Post = tink.QueryString.parse('title=Example+Post&body=This+is+an+example&tags[0]=foo&tags[1]=bar');
    trace(post);//{ title: 'Example Post', body: 'This is an example', tags: ['foo', 'bar'] }

    }
    }

gives following error at compilation:

     /Users/postite/haxe/haxe_libraries/tink_querystring/0.6.0/github/8eee7f83e2f60606415ff09062423117ff839056/src/tink/querystring/macros/GenParser.hx:122: characters 26-33 : error: Cannot unify final and non-final fields
    /Users/postite/haxe/haxe_libraries/tink_querystring/0.6.0/github/8eee7f83e2f60606415ff09062423117ff839056/src/tink/querystring/macros/GenParser.hx:122: characters 26-33 :  have: ({ name: Dynamic }) -> ...
    /Users/postite/haxe/haxe_libraries/tink_querystring/0.6.0/github/8eee7f83e2f60606415ff09062423117ff839056/src/tink/querystring/macros/GenParser.hx:122: characters 26-33 :  want: ({ name: Dynamic }) -> ...
    /Users/postite/haxe/haxe_libraries/tink_querystring/0.6.0/github/8eee7f83e2f60606415ff09062423117ff839056/src/tink/querystring/macros/GenParser.hx:122: characters 26-33 : For function argument 'name'
     The terminal process terminated with exit code: 1

**Comment by serjek** [comment]
still repro with latest tink_core

**Comment by CedX** [comment]
Same issue here (Haxe 4.2.2, tink_core 2.0.1, tink_querystring 8eee7f83e2f60606415ff09062423117ff839056, haxetink/tink_web@bca4eadb3311e2aa613850f50ae1bdfe0acd8dd3).
I'm currently using the fix from #19 to avoid this issue.

**Comment by CedX** [comment]
Thanks a lot @back2dos 🎉
