### ISSUE TITLE
tink_url Dependency 

### ISSUE THREAD

**Issue by kevinresol** [haxetink/tink_querystring#4]
I wonder why this lib depends on tink_url while I think it should be another way round.

**Comment by back2dos** [comment]
This lib requires `tink.url.Portion` to work. It is also quite opinionated about how to compose / decompose querystrings, which `tink_url` handles merely on a superficial level. The latter is entirely macro free (in some arcane set up I do use it to parse git remotes at compile time).

I'd say `tink_querystring` is to `tink_url` what `tink_web` is to `tink_http`, but then again I might see this totally backwards :D

**Comment by kevinresol** [comment]
alright that make sense
